language: python
python:
  - "3.6.9"
  - "3.7.6"
  - "3.8.1"
sudo: required
dist: bionic
install:
  - "pip install nose"
  - "pip install pycodestyle pydocstyle pyflakes"
  - "pip install coverage"
  - "pip install codacy-coverage"
  - "pip install collective.checkdocs Pygments"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=plyara --cover-xml
  - pycodestyle plyara/*.py
  - pycodestyle setup.py
  - pycodestyle tests/unit_tests.py
  - pydocstyle plyara/__init__.py
  - pydocstyle plyara/core.py
  - pydocstyle plyara/exceptions.py
  - pydocstyle plyara/utils.py
  - pydocstyle tests/unit_tests.py
  - pydocstyle plyara/command_line.py
  - pydocstyle setup.py
  - pyflakes plyara/core.py
  - pyflakes plyara/exceptions.py
  - pyflakes plyara/command_line.py
  - pyflakes plyara/utils.py
  - pyflakes setup.py
  - pyflakes tests/unit_tests.py
  - python setup.py checkdocs
after_success:
  - python-codacy-coverage
